from app.api.auth import router as auth_router
from app.api.tournaments import router as tournaments_router
from app.api.wallet import router as wallet_router
from app.api.matches import router as matches_router
from app.api.referrals import router as referrals_router
from app.api.users import router as users_router
from app.api.admin import router as admin_router
from app.api.auto_move import router as auto_move_router
from app.api.withdrawals import router as withdrawals_router
from app.api.admin_config import router as admin_config_router
from app.api.feature_flags import router as feature_flags_router
from app.api.admin_audit import router as admin_audit_router
from app.api.notifications import router as notifications_router
from app.api.metrics_api import router as metrics_router
from app.api.queue import router as queue_router
